### ISSUE TITLE
Fix Jenkins Job to build and deploy nightly images

### ISSUE THREAD

**Issue by ricardozanini** [apache/incubator-kie-kogito-serverless-operator#300]
### Describe the bug

Currently, Apache Jenkins has not been working since the migration from kiegroup. After an initial assessment, we need the following:

1. Remove OpenShift tests since we don't have a cluster yet (we may add this later once we have a cluster to run)
2. Assess the tooling to build the operator image in the current infrastructure
3. Change the build stage to use the tooling we have in Apache Jenkins

### Expected behavior

`kogito-serverless-operator-deply` job to work on Apache Jenkins: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/nightly/job/kogito-serverless-operator-deploy

### Actual behavior

See description.

**Comment by ricardozanini** [comment]
Now we get an other error:

```
ERROR: Could not find credentials entry with ID 'OPENSHIFT_API'
```

**Comment by ricardozanini** [comment]
Still seeing problems, now with free local port in the registry.

**Comment by domhanak** [comment]
Today the failure was the E2E tests execution:
https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/nightly/job/kogito-serverless-operator.e2e.minikube/1/console

I am looking into that, most probably we just need to fix the git command and disable the tests as proposed.

**Comment by domhanak** [comment]
after #323 and #349 the nightly builds are working well.
