### ISSUE TITLE
Production profile build failing with a configured subflow 

### ISSUE THREAD

**Issue by dmartinol** [apache/incubator-kie-kogito-serverless-operator#307]
### Describe the bug

**Steps**
In OpenShift, deploy a SonataFlow instance `test` with `prod` profile and include a subflow with a user defined ConfigMap called `test-subflow`.
Mount the ConfigMap in the SonataFlow instance using:
```yaml
spec:
  resources: 
    configMaps:
      - configMap:
          name: escalation-subflow 
```

### Expected behavior

The Build generates an image building the `test` SWF and the `test-subflow` SWF, and all the mounted user properties (if any)

### Actual behavior

The build fails with an error:
```
NoSuchFileException:
            /home/kogito/serverless-workflow-project/src/main/resources/specs/jira.yaml
```
Looking into the Pod, the expected folder structure is missing>
```
sh-4.4# ls /home/kogito/serverless-workflow-project/resources
ls: cannot access '/home/kogito/serverless-workflow-project/resources': No such file or directory
sh-4.4# ls /home/kogito/
ls: cannot access '/home/kogito/': No such file or directory
```

**Comment by ricardozanini** [comment]
Depends on https://github.com/apache/incubator-kie-kogito-images/pull/1711
