### ISSUE TITLE
Rename "prod" profile to "preview"

### ISSUE THREAD

**Issue by ricardozanini** [apache/incubator-kie-kogito-serverless-operator#319]
### Description

Calling "prod" profile might confuse users into thinking that the operator can deliver an immutable image ready for production use cases. While this can be true in simplistic scenarios, real use cases require much more than the simple embedded build platform that we currently ship with the operator.

On Kubernetes we rely on Kaniko, on OpenShift on a simple `BuildConfig` object. This setup is more for a "preview" or staging use cases where user wants a glimpse of what it will look like a lighter image and immutable workflow on their topology.

Real use cases must rely on external build tooling. An example can be seen in this repo: https://github.com/flows-examples/gitops

This proposal is to change the `prod` profile naming and internal modules to `preview`. The profile capable to analyze and deploy an external built image we will call internally to `gitops` and it's activated as long as there's a `.spec.podTemplate.flowContainer.image` valid attribute set.

### Implementation ideas

Simply renaming and refactoring. No new features to add. Also, the guides must be updated accordingly.

**Comment by ricardozanini** [comment]
@tchughesiv @masayag @krisv @wmedvede fyi

**Comment by wmedvede** [comment]
Imagine that I want to work with one of this simplistic scenarios, I just have a simple workflow, and I don't want (or really don't need) to setup such external build tooling.
Which profile should I use in these cases?

**Comment by ricardozanini** [comment]
Preview
