### ISSUE TITLE
Temporary use of the nightly images

### ISSUE THREAD

**Issue by wmedvede** [apache/incubator-kie-kogito-serverless-operator#346]
### Describe the bug

The selector produced for the jobs service and data index service, is the same "sonataflow-platform". Which makes not possible for each service to pick the corresponding pods, etc.

**Comment by masayag** [comment]
@wmedvede should this be closed as a duplicate of https://github.com/apache/incubator-kie-kogito-serverless-operator/issues/340 ? or the other way around?

**Comment by tchughesiv** [comment]
my vote would be to close this one given we've already reviewed/approved the PR for https://github.com/apache/incubator-kie-kogito-serverless-operator/issues/340

**Comment by wmedvede** [comment]
I have merged @masayag @tchughesiv and keep this one only to use the nightly images.

**Comment by wmedvede** [comment]
resolved: https://github.com/apache/incubator-kie-kogito-serverless-operator/pull/347
