### ISSUE TITLE
allow user customization on generated knative resources

### ISSUE THREAD

**Issue by RichardW98** [apache/incubator-kie-kogito-serverless-operator#355]
### Description

in https://github.com/apache/incubator-kie-kogito-serverless-operator/pull/350, a central default broker is used for all sinkbindings and triggers. It is expected that user can have the flexibility to manage the config of generated knative resources from Sonataflow/SonataflowPlatform CR

### Implementation ideas

as suggested [here](https://docs.google.com/document/d/1GrVKanrwsEr3r1VlepErHOnq8dVI4dr8EeQcecTvqBE/edit?disco=AAAA9zJbm88). user should be able to specify different brokers for events:
`spec:
events:
sink:
... # YOUR PROPOSAL
triggers:
- event: <EVENT NAME>
broker: <BROKER NAME>`

where all the options can still have a defined defaults from spec.sink

**Comment by jianrongzhang89** [comment]
This capability has been supported in  https://github.com/apache/incubator-kie-kogito-serverless-operator/issues/368, and this issue is no longer needed.
