### ISSUE TITLE
Omit imagePullPolicy from the deployment created by Sonata operator

### ISSUE THREAD

**Issue by rgolangh** [apache/incubator-kie-kogito-serverless-operator#359]
### Describe the bug

The operator sets imagePullPoiicy to `Always`. This is against the default of openshift, which is ifNotPresent , and against
the k8s default which should be also ifNotPresent in case a tag or SHA is used.

### Expected behavior

if there's a tag which is not 'latest' , then omit the imagePullPolicy completely

### Actual behavior

imagePullPolicy is set in the generated deployment

### How to Reproduce?

1.Deploy any sonataflow resource, e.g greeting and see the default

oc create -f  https://raw.githubusercontent.com/rgolangh/serverless-workflows-helm/main/charts/workflows/charts/greeting/templates/01-sonataflow_greeting.yaml

2. oc get deployments greeting  -o jsonpath={.spec.template.spec.containers[]}  | jq '.imagePullPolicy'

### Output of `uname -a` or `ver`

k8s kind 0.20

### Additional information
https://issues.redhat.com/browse/FLPATH-892
_No response_

**Comment by rgolangh** [comment]
@ricardozanini 
The operator image used is masayag/kogito-serverless-operator with a fix for missing properties. I'll go hunt the base image used and paste here.

**Comment by ricardozanini** [comment]
I understand the issue, but not why you mention the base image used. 🤔

This is a fairly easy fix, I'll take a look today.

**Comment by rgolangh** [comment]
> I understand the issue, but not why you mention the base image used. 🤔

Wanted to be a nice citizen and help with the version I used, in case this was handled already or just plane non sense :wink: 

> This is a fairly easy fix, I'll take a look today.
