### ISSUE TITLE
List of pods for the operator Deployment is wrong

### ISSUE THREAD

**Issue by dmartinol** [apache/incubator-kie-kogito-serverless-operator#366]
### Describe the bug

When we deploy the operator in a cluster where other operators are installed, the list of pods for the `sonataflow-operator-controller-manager` Deployment may contain pods that are not related to this operator.
The query performed to fetch the matching pods is including pods that are not managed by the SonataFlow operator, because it's using a filter on a label that is also adopted by others, as in:
```
https://<CLUSTER_APISERVER>/api/kubernetes/api/v1/namespaces/openshift-operators/pods?limit=250&labelSelector=control-plane%3Dcontroller-manager&cluster=local-cluster
```
For instance, this is an example of the same query performed using the CLI:
```
% oc get pods -l control-plane=controller-manager
NAME                                                      READY   STATUS    RESTARTS         AGE
argocd-operator-controller-manager-dfc7f9499-jx4cw        1/1     Running   37 (2d17h ago)   14d
patterns-operator-controller-manager-59dbb77564-s4mpt     2/2     Running   0                41h
sonataflow-operator-controller-manager-6946b46b76-vb6hk   2/2     Running   0                39s
```

**Comment by ricardozanini** [comment]
This is the label we should add:

![image (6)](https://github.com/apache/incubator-kie-kogito-serverless-operator/assets/1538000/11b565df-c154-46fa-bbc0-14c34a97663e)
