### ISSUE TITLE
Create knative resources for DataIndex and JobService

### ISSUE THREAD

**Issue by ricardozanini** [apache/incubator-kie-kogito-serverless-operator#368]
### Description

As depicted in https://sonataflow.org/serverlessworkflow/latest/use-cases/timeout-showcase-example.html#_architecture.  there should be sinkbindings and triggers automatically created for the commute between workflow deployments and Dataindex/JobService

Particularly, the Sinkbindings and triggers are mandatory for Dataindex.
for Jobservice, those objs need to be created depending on time-based events detected in workflow payload including timeout and sleep as described [here](https://sonataflow.org/serverlessworkflow/latest/job-services/core-concepts.html#integration-with-the-workflows)

**Comment by jianrongzhang89** [comment]
I will look into this issue.

**Comment by jianrongzhang89** [comment]
Started on a draft ADR

**Comment by gabriel-farache** [comment]
Just to have the link to the PR https://github.com/apache/incubator-kie-kogito-serverless-operator/pull/467
