### ISSUE TITLE
Support Multiple Knative Sinks

### ISSUE THREAD

**Issue by ricardozanini** [apache/incubator-kie-kogito-serverless-operator#369]
### Description

currently due to the K_SINK var injection, we can only support one sinkbinding per deployment. To support the flexibility of multiple event destinations from producers within single deployment. We need to find out a way to support multiple sinks.

**Comment by jianrongzhang89** [comment]
@ricardozanini only one sinkbinding can be allowed for an application. Creating multiple sinkbindings against the same application can lead to issues for the cluster (https://github.com/knative/eventing/issues/5749). Hence I think this issue should be rejected.
