### ISSUE TITLE
Creation of Knative Sinks in SonataFlow CRD

### ISSUE THREAD

**Issue by ricardozanini** [apache/incubator-kie-kogito-serverless-operator#370]
### Description

In the first version of [knative eventing objs provision feature](https://github.com/apache/incubator-kie-kogito-serverless-operator/pull/350), we assume the sink pre-existed and even hardcoded 'default' as broker for triggers. 

It is preferred to extend the flexibility for user to specify the configuration of sinks for events of their workflows. e.g. in dev profile, they can use inMemoryChannel while kafka and other types of brokers can be supported/configured in prod

**Comment by gabriel-farache** [comment]
I drafted a first version of the ARD https://docs.google.com/document/d/1qB6eo58fHMHPfE28DCqBCwzIolkYxM-M5KHBoFNpykI/edit#heading=h.ds8q4xtkmu64
@ricardozanini @wmedvede @fjtirado COuld you take a look?

**Comment by ricardozanini** [comment]
Our platform will avoid managing third-party objects that can - and will - change their API and have too many configuration and entry points, like a Broker. The user/admin must be responsible for their infra, customization, and setup. What we do is integrate with the platform and compose, as we do with triggers, sink bindings, and so on. That's why we do not manage a database, a Prometheus or Grafana installation, builds, and so forth.
