### ISSUE TITLE
Break the current operator's configuration into custom and managed properties

### ISSUE THREAD

**Issue by domhanak** [apache/incubator-kie-kogito-serverless-operator#381]
### Description

*Summary*
Currently, the same {{ConfigMap}} holds managed (what we currently call "immutable") and custom properties defined by users.

A few application properties cannot be changed by users, being managed by the operator such as the HTTP port.

We should convert those properties to environment properties and set them to the deployment workflow. These env properties must be immutable and managed by the operator. Env properties override the application.properties mounted currently by the operator. See https://quarkus.io/guides/config-reference#configuration-sources

The current ConfigMap will be solely for user custom properties.

 

*Acceptance criteria:*

    After a successful deployment of the SonataFlow instance ABC, the ABC-props ConfigMap is still owned by this instance but not updated by the Sonata Flow operator
    All the immutable properties defined by the operator are mapped to env variables in the ABC Deployment owned by the SonataFlow instance (in the spec.template.spec.containers[0].env section)
    If any variable defined in the spec.podTemplate.container.env section of the SonataFlow instance match one of the immutable variable names, the value mapped in the ABC Deployment will be the one defined by the operator
        In this case, an Event of type Warning is created for the SonataFlow instance

**Comment by domhanak** [comment]
@dmartinol FYI, moved the description to community for visibility.

**Comment by dmartinol** [comment]
> @dmartinol FYI, moved the description to community for visibility.

@domhanak after some failed attempts, we've update the design to use a `profile aware properties file` to hold the managed properties, instead. The user guide will be updated by this [PR](https://github.com/apache/incubator-kie-kogito-docs/pull/527), but I believe the description of this issue must be aligned with the implementation.
