### ISSUE TITLE
Opt-in deploy SonataFlow as Knative Serving service instead of k8s Deployments

### ISSUE THREAD

**Issue by ricardozanini** [apache/incubator-kie-kogito-serverless-operator#385]
### Description

Currently, the operator deploys workflows as regular Kubernetes Deployments. In some use cases, deploying a workflow as a Knative Serving resource makes sense.

- Assess the possibility of deploying workflows as Knative Serving services by default if Knative is installed in the cluster
- Add the possibility for users to opt-in to deploying as a ksvc or k8s deployment by labeling the CR.
- Once labeled and deployed, this attribute must be immutable. We may assess the possibility of changing this field later in the field
- Initially, revisions handling is out of scope, the operator won't reconcile this field so that users can change it based on their requirements. An assessment of revisions in the platform can be done later

**Comment by masayag** [comment]
What about providing an option for deployment method (knative service or k8s deployment) at the SonataflowPlatform level? so for each production profile workflow, the same will method will be applied.

**Comment by ricardozanini** [comment]
We might add that in the future, sure.
