### ISSUE TITLE
Provide a method to set labels to the k8s resources of the workflow

### ISSUE THREAD

**Issue by masayag** [apache/incubator-kie-kogito-serverless-operator#410]
### Description

We'd like a way that enables us to label K8s resources related to the Sonataflow CR. E.g have the same labels appear in k8s deployment, pod, service, route and so.

Today, only default labels are applied to those resources (`app=workflow-name`, `sonataflow.org/workflow-app=`,  `sonataflow.org/service=`)

A private case of it is Backstage plugins that interact with K8s cluster (ci, gitops and others).
In backstage, to view workflow resources related to a component under the CI (tekton) and K8s tabs, a specific label should be set on the pods (e.g. `backstage.io/kubernetes-id=application-onboarding`).

By enabling the label, the user can view pipelines related to the workflow as in the attached image:
For the CI:
![Selection_129](https://github.com/apache/incubator-kie-kogito-serverless-operator/assets/316242/c61fce33-9e59-4a7b-8db9-d8e2872904a3)
And for K8s:
![Selection_130](https://github.com/apache/incubator-kie-kogito-serverless-operator/assets/316242/c2c937ca-25a5-47db-b06a-c7f5edc187d7)

### Implementation ideas

* Propagate Sonataflow CR labels to the k8s resources.
* Extend the Sonataflow CR API to support it.

I'm in favor of the first option.

**Comment by ricardozanini** [comment]
I think we can propagate the labels from the `SonataFlow` CR to the resources. So any custom labels added there by users would also be added to the resources. Is this a reasonable approach for you?

**Comment by masayag** [comment]
> I think we can propagate the labels from the `SonataFlow` CR to the resources. So any custom labels added there by users would also be added to the resources. Is this a reasonable approach for you?

That's sounds great :-)

**Comment by ricardozanini** [comment]
@masayag go ahead and send a PR! :D
