### ISSUE TITLE
Migrate operator images from Dockerfile to Cekit

### ISSUE THREAD

**Issue by ricardozanini** [apache/incubator-kie-kogito-serverless-operator#422]
### Description

To bring ubiquity to our platform, repositories, and ecosystem we should migrate our Dockerfile build model to Cekit since it's the tool used in `kogito-images` to this date. Also, the `Makefile` requires a few refactors to make it easier to understand.

### Implementation ideas

Use `kogito-images` as the basis for this implementation.

**Comment by davidesalerno** [comment]
Could it be useful to use the cekit image descriptors  [osl-image-prod.yaml](https://github.com/apache/incubator-kie-kogito-serverless-operator/blob/main/osl-image-prod.yaml) and [osl-bundle-prod.yaml](https://github.com/apache/incubator-kie-kogito-serverless-operator/blob/main/osl-bundle-prod.yaml) as an example togheter to the `kogito-images` stuff?

**Comment by ricardozanini** [comment]
@davidesalerno not sure if I'm following 🤔 

Those are modules related to Red Hat projects that we removed once we moved to ASF.

> Could it be useful to use the cekit image descriptors [osl-image-prod.yaml](https://github.com/apache/incubator-kie-kogito-serverless-operator/blob/main/osl-image-prod.yaml) and [osl-bundle-prod.yaml](https://github.com/apache/incubator-kie-kogito-serverless-operator/blob/main/osl-bundle-prod.yaml) as an example togheter to the `kogito-images` stuff?
