### ISSUE TITLE
Workflows built in SFCP namespace always use latest tag for builder image

### ISSUE THREAD

**Issue by domhanak** [apache/incubator-kie-kogito-serverless-operator#486]
### Describe the bug

Problem seems to be rooted in SFCP not using  values from:
ConfigMap of operator -> controllers_cfg.yaml
and just use the default builder configmap dockerfile.

### Expected behavior

SFCP workflows use the builder image from controllers-config ConfigMap of operator -> controllers_cfg.yaml

### Actual behavior

SFCP workflows use the builder image from builder configmap

### How to Reproduce?

1.     Deploy SFP with JS and DI postgresql ephemeral
2.     Deploy SFCP in separate namespace and reference above SFP
3.     Create new SF-Greeting in the SFCP NS
4.     Check log of the build ->It will use <builder-image>:latest
5.     Create new SF-Greeting-2 in SFP NS
6.     Check log of the build -> it will use <budilder-image>:9.99.0
7.     Inspect NS where operator is runnning, find configmap of builder
8.     You can see there is a FROM <builder_image>:latest
9.     Change this line to some other image
10.     Repeat from point, but just restart the builds of the SF CR's

**Comment by ricardozanini** [comment]
@domhanak Actually, the `SonataFlowClusterPlatform` is a cluster resource, hence it does not have a namespace. What happened here is that the operator created a default `SonataFlowPlatform` in the namespace of the workflow `SF-Greeting`. This automatic created platform is missing the default configuration. Please check my PR, it fixed the issue.

**Comment by domhanak** [comment]
@ricardozanini Yea apologies for that, what I meant is simply a new NS on a cluster that has SFCP set. Will take a look.
