### ISSUE TITLE
Some lables are missing on some of the resources the operator creates

### ISSUE THREAD

**Issue by rgolangh** [apache/incubator-kie-kogito-serverless-operator#509]
### Describe the bug

As part of the work on #483 @wmedvede caught some resources which are not reconciled with the common lables:
- managed properties
- the build pod
- workflow with dev profile, missing platform
- the user provided config map 

### Expected behavior

All the resources created by the operator directly should have lables to tie them to the platform and their respected workflows. The case of the pod created by the builder is something I'm not sure about though.
Resource the user provider, like configmap we should stongly consider to label too, because it is also part of a workflow.

### How to Reproduce?

Deploy a greeing workflow with dev and prod profile, on openshift (for the build) and k8s

**Comment by ricardozanini** [comment]
Fixed on https://github.com/apache/incubator-kie-kogito-serverless-operator/pull/482
