### ISSUE TITLE
errorMessage metadata is not parsed correctly

### ISSUE THREAD

**Issue by gabriel-farache** [apache/incubator-kie-kogito-serverless-operator#532]
### Describe the bug

When applying the enclosed sonataflow CR, the following error is thrown:
```
The SonataFlow "m2k" is invalid: spec.flow.states[12].metadata.errorMessage: Invalid value: "string": spec.flow.states[12].metadata.errorMessage in body must be of type object: "string"
```
I removed the setting of the metadata from the CR and the apply works.

When the workflow runs with the image containing the `errorMessage` metadata, there is no issue and the workflow behave as expected, I think this is purely an issue on the operator side

### Expected behavior

No issue when applying the manifest

### Actual behavior

Unexpected error 
```
The SonataFlow "m2k" is invalid: spec.flow.states[12].metadata.errorMessage: Invalid value: "string": spec.flow.states[12].metadata.errorMessage in body must be of type object: "string"
```
while applying the manifest

### How to Reproduce?

1. Apply the manifest [04-sonataflow_m2k.zip](https://github.com/user-attachments/files/16966035/04-sonataflow_m2k.zip)
2. See the error

**Comment by gabriel-farache** [comment]
In case there is an issue with mounted volumes, in this archives, you have all manifests needed [serverless-workflow-move2kube-manifests.zip](https://github.com/user-attachments/files/16966052/serverless-workflow-move2kube-manifests.zip)

**Comment by ricardozanini** [comment]
Depends on:
- https://github.com/serverlessworkflow/sdk-go/pull/211

**Comment by ricardozanini** [comment]
Also depends on:

- https://github.com/serverlessworkflow/sdk-go/pull/214
