### ISSUE TITLE
Make the operator configure the kogito events grouping by default in preview and gitops workflow deployments

### ISSUE THREAD

**Issue by fjtirado** [apache/incubator-kie-kogito-serverless-operator#548]
### Description

https://github.com/apache/incubator-kie-issues/issues/1457 added the possibility to group event publishing. 
In order to enable this functionality, property `kogito.events.grouping` should be set to true. 
In addition to that, it would be nice to investigate if there is any application limit to the size of knative messages, to evaluate increasing it when the property is enabled

**Comment by wmedvede** [comment]
Implemented by: #551
